import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'ngASATraining';
  captions = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sem tortor, imperdiet non tincidunt sodales, lobortis at orci. Donec ultricies ullamcorper nisl, vel ultricies eros sagittis ut. Nullam eget lectus nec tellus blandit rutrum. Phasellus euismod nulla in libero pellentesque euismod. Nulla dictum tortor quis augue aliquam, ut fermentum diam tincidunt. Morbi finibus, velit sit amet congue bibendum, diam risus accumsan turpis, ut dictum orci sapien ultrices justo. Integer ut ipsum maximus, sodales nibh nec, tempor eros. Duis sapien quam, euismod nec gravida ut, bibendum nec est. Vestibulum accumsan orci at mauris luctus ornare. Mauris pharetra, libero a iaculis mollis, arcu dui ultricies quam, eu consequat sem felis vitae eros. Sed vel laoreet leo. Quisque quis fringilla metus.

  Sed id gravida felis. In cursus, turpis ac tincidunt luctus, purus justo pharetra sem, et tristique ligula nisi viverra lorem. Nullam sit amet ultricies sapien. Sed dignissim tincidunt ipsum. Praesent convallis convallis orci eget egestas. Integer sed lorem blandit, lacinia velit nec, imperdiet ipsum. Duis consequat lectus justo, ac pellentesque nisl consectetur hendrerit. Nullam vel purus at velit fringilla venenatis vitae at quam. Ut tristique suscipit rhoncus. Proin placerat, neque quis vestibulum tristique, erat tellus tristique tellus, in condimentum lacus dolor nec lorem. Maecenas feugiat tortor at tincidunt rhoncus. Donec sit amet ornare enim. Vivamus laoreet in nisl quis sollicitudin. Mauris nec velit tortor.
  
  Ut volutpat ipsum et dui egestas, ut vehicula dui dictum. Proin eget lectus vitae dolor porta ultricies. Ut nec lectus porttitor, mattis purus eu, egestas ex. Aliquam in orci non orci hendrerit mollis. Maecenas id mauris condimentum, rhoncus purus vel, fermentum elit. In ipsum mi, fermentum eu felis non, eleifend elementum tellus. Integer sollicitudin sapien nisi, eget interdum ante lobortis non. Nullam aliquet tristique enim. Vestibulum in euismod dui.
  
  Curabitur tempor, ligula eget laoreet tincidunt, eros magna ornare dolor, vitae interdum felis augue sed eros. Aenean aliquet, ipsum eget euismod facilisis, tortor libero laoreet ante, non vehicula sem leo vel tellus. Vivamus purus sapien, elementum a tincidunt sed, interdum a quam. Maecenas interdum rutrum facilisis. Sed tempor, est ut vestibulum semper, magna sem efficitur ante, sit amet elementum nisl risus et nunc. Curabitur facilisis eleifend sem vitae placerat. Mauris a ullamcorper libero. Vivamus ultrices augue augue, nec bibendum odio congue sed. Sed sit amet efficitur sapien, finibus euismod justo. Donec sed nibh tempor, congue nibh eu, dictum erat. Aliquam eu leo auctor, viverra ipsum in, pellentesque sem. Maecenas interdum ac nisl malesuada posuere. Fusce cursus ligula eget elementum rhoncus.
  
  Praesent ornare feugiat diam, vel aliquam nulla pretium eget. Phasellus at turpis eget tortor pellentesque pellentesque. Phasellus posuere volutpat lacus, nec egestas turpis aliquet et. Maecenas accumsan metus lacus, non lacinia metus mollis vitae. In a rutrum est, in auctor purus. Sed et libero non turpis tincidunt rutrum. Pellentesque eget dignissim nibh, ac posuere turpis. Donec dictum felis at orci luctus imperdiet. Etiam et pulvinar neque.
  
  Nam fermentum nibh enim, elementum sollicitudin neque elementum sed. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus consectetur, justo eget efficitur pellentesque, turpis velit hendrerit justo, vel varius risus diam nec dolor. Aenean eu dignissim mi. Sed mi sapien, finibus vel semper nec, ornare eu dolor. Integer tortor massa, maximus id enim et, molestie volutpat felis. In sed odio tortor. Aenean tincidunt pellentesque nulla. Etiam diam risus, fringilla quis magna ut, pulvinar scelerisque velit. Aliquam at euismod mi. Maecenas in convallis nulla. Proin blandit diam leo, pharetra sollicitudin lorem gravida sagittis. Donec ac lectus placerat, commodo purus quis, vehicula purus. Donec ac elementum neque. Suspendisse dui est, porta sit amet sapien et, ultrices egestas nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
  
  Praesent a orci tortor. Donec nec euismod sapien. Proin pretium metus eu nulla congue, vulputate bibendum elit imperdiet. In lectus ex, cursus in sapien volutpat, tempor feugiat lacus. Pellentesque in ligula magna. Etiam et elit eleifend, ullamcorper lacus ut, fringilla nibh. Nullam egestas erat ac odio sodales porttitor. Etiam hendrerit, libero sed placerat porta, nisl leo blandit lorem, id pulvinar eros ipsum eget purus. Integer in rutrum erat.
  
  Cras sed dolor tincidunt, tempor erat aliquam, ultricies velit. Nulla at arcu bibendum, ornare neque ac, scelerisque nulla. Nulla tincidunt, lorem sit amet auctor tempus, felis purus porta risus, eu malesuada odio augue vel risus. Duis dignissim ullamcorper risus, ac egestas lorem pulvinar id. Sed ultricies, libero sed blandit lobortis, elit purus dignissim neque, vitae laoreet mauris quam a nisl. Sed a leo finibus, egestas ligula quis, dignissim eros. Aliquam dolor felis, ornare eu tincidunt at, cursus ac ante. Curabitur luctus et nisl non cursus. In interdum nisi vitae rhoncus viverra. Aliquam eget dolor nisi. Quisque a pretium felis. Quisque gravida facilisis massa, nec tristique nibh bibendum in. Quisque venenatis est elementum hendrerit consectetur.
  
  Phasellus at dictum ligula, in feugiat massa. Vestibulum lacinia non est at placerat. Cras non finibus odio, sit amet laoreet erat. Nunc vitae lacus pharetra, tristique nunc in, sodales dui. Nullam commodo magna non risus aliquam ultrices sit amet at quam. Mauris faucibus felis non mi maximus, consectetur semper tortor placerat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec vel dui justo. Praesent mollis suscipit dapibus. Aenean tortor nulla, ultricies a metus id, lobortis lobortis erat. Morbi iaculis elit at ante vehicula, nec tincidunt augue molestie. Sed convallis magna ornare magna dictum, ut pulvinar urna molestie. Etiam accumsan ante sit amet ligula venenatis, id convallis urna posuere. Mauris sed neque laoreet, volutpat est nec, molestie massa. Maecenas blandit mauris enim. Nulla ac tristique libero.
  
  Praesent et erat sed nisi ultrices suscipit vel nec arcu. In hac habitasse platea dictumst. Sed nec ante tincidunt, porttitor velit eget, tincidunt leo. Quisque vitae feugiat enim, laoreet porttitor ligula. Aenean accumsan venenatis quam. Pellentesque id lobortis lectus, ut condimentum dui. Nam vitae massa luctus, dapibus libero nec, varius tortor. Integer porttitor quam vitae dolor vulputate maximus. Nunc at pulvinar turpis. Nam porttitor tortor quis nunc gravida, porta consectetur urna ultrices. Etiam non diam et eros vehicula tincidunt sed id mi.`
}
